[package]
name = "toktok"
version = "0.1.0"
authors = ["Jannik Obermann <jannik.obermann@gmail.com>"]
edition = "2018"
description = "toktok - WIP"
license = "MIT"
repository = "https://github.com/jannik4/toktok"

[dependencies]
